"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app --plist Info.plist
"""
import shutil
from setuptools import setup

APP = ['ZwiftWorlds.py']
DATA_FILES = [('', ['img'])]
OPTIONS = {'packages': ['tkinter'],
            'includes': ['tkinter'],
            'iconfile':'img/ZwiftWorldsUI.icns'}
# auto-clean
try:
    print("Cleaning ./build...")
    shutil.rmtree("./build")
    print("Cleaning ./build... Done.")
except OSError as e:
    print("./build already cleaned. >> " + e.strerror)

try:
    print("Cleaning ./dist...")
    shutil.rmtree("./dist")
    print("Cleaning ./dist... Done.")
except OSError as e:
    print("./dist  already cleaned. >> " + e.strerror)

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
